<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Discord.Addons.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mutterblack.Discord.Test" />
  </ItemGroup>

</Project>
